---
openapi: 3.0.3
info:
  title: contactify-quark API
  version: 1.0.0-SNAPSHOT
paths:
  /contact:
    get:
      tags:
      - Contact Resource
      parameters:
      - name: search
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme: []
    post:
      tags:
      - Contact Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme: []
  /contact/{id}:
    put:
      tags:
      - Contact Resource
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme: []
    delete:
      tags:
      - Contact Resource
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme: []
  /user/login:
    post:
      tags:
      - Account Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequestDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseDTO'
  /user/ping:
    get:
      tags:
      - Account Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /user/register:
    post:
      tags:
      - Account Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          format: int64
          type: integer
        username:
          type: string
        password:
          type: string
        roles:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/AccountRole'
    AccountRole:
      type: object
      properties:
        id:
          format: int64
          type: integer
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'
        role:
          type: string
    AuthRequestDTO:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponseDTO:
      type: object
      properties:
        username:
          type: string
        authToken:
          type: string
    Contact:
      type: object
      properties:
        id:
          format: int64
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
